name: Release on GitHub & PyPI

on:
  push:
  # pull_request:
  # release:
  #   types:
  #     - published

jobs:

  build-wheel-osx-windows:
    runs-on: ${{ matrix.os }}
    name:  Build wheels [${{ matrix.os }}]
    strategy:
      fail-fast: false
      matrix:
        python-version:
          - 3.8
        os:
          - macos-latest
          - windows-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      # - name: Set ownership
      #   run: |
      #     # Workaround for https://github.com/actions/runner/issues/2033
      #     # this is to fix GIT not liking owner of the checkout dir
      #     chown -R $(id -u):$(id -g) $PWD
      #     git submodule update

      # - uses: conda-incubator/setup-miniconda@v2
      #   with:
      #     miniforge-variant: Mambaforge
      #     miniforge-version: latest
      #     channels: conda-forge
      #     python-version: ${{ matrix.python-version }}
      #     activate-environment: proxsuite

      # - name: Install dependencies [Conda]
      #   shell: bash -l {0}
      #   run: |
      #     # Workaround for https://github.com/conda-incubator/setup-miniconda/issues/186
      #     conda config --remove channels defaults
      #     mamba install doxygen graphviz eigen simde gcc cmake compilers

      - name: Install cibuildwheel
        shell: bash -l {0}
        run: |
          pip install cibuildwheel
      
      - name: Build wheels
        run: python -m cibuildwheel --output-dir wheelhouse scripts/pip
        
      - name: Inspect wheelhouse folder
        run: ls -lah wheelhouse/

      # - name: Print environment [Conda]
      #   shell: bash -l {0}
      #   run: |
      #     conda info
      #     mamba list
      #     env

      - name: Build wheels
        run: python -m cibuildwheel --output-dir wheelhouse
      