name: Release on GitHub & PyPI

on:
  # pull_request:
  # release:
  #   types:
  #     - published
  push:

jobs:
  build-wheel:
    runs-on: ${{ matrix.os }}
    name: Build ${{ matrix.os }} ${{ matrix.python-version }}
    strategy:
      matrix:
        python-version: ["3.8"]
        # python-version: ["3.8", "3.9", "3.10"]
        os: [ubuntu-latest]
        # os: [ubuntu-latest, macos-latest]

    steps:
      - name: Set docker for linux
        if: contains(matrix.os, 'ubuntu')
        uses: docker://quay.io/pypa/manylinux_2_24_x86_64

      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Set ownership
        run: |
          # Workaround for https://github.com/actions/runner/issues/2033
          # this is to fix GIT not liking owner of the checkout dir
          chown -R $(id -u):$(id -g) $PWD
          git submodule update

      # - uses: actions/setup-python@v2
      #   if: contains(matrix.os, 'ubuntu')
      #   with:
      #     python-version: ${{ matrix.python-version }}

      - uses: conda-incubator/setup-miniconda@v2
        if: contains(matrix.os, 'macos')
        with:
          miniforge-variant: Mambaforge
          miniforge-version: latest
          channels: conda-forge
          python-version: ${{ matrix.python-version }}
          activate-environment: proxsuite

      - name: Install dependencies [Conda]
        if: contains(matrix.os, 'macos')
        shell: bash -l {0}
        run: |
          # Workaround for https://github.com/conda-incubator/setup-miniconda/issues/186
          conda config --remove channels defaults
          mamba install doxygen graphviz eigen simde cmake compilers
          pip3 install auditwheel

      - name: Install dependencies [apt]
        if: contains(matrix.os, 'ubuntu')
        shell: bash -l {0}
        run: |
          sudo apt-get update
          # sudo apt-get -y install libsimde-dev libeigen3-dev
          sudo apt-get -y install libeigen3-dev

      # - name: Use clang for macos
      #   if: contains(matrix.os, 'macos')
      #   shell: bash -l {0}
      #   run: |
      #     # Need to replace compiler by hand
      #     sed -i.bu 's/gcc/clang/' pyproject.toml

      - name: Print environment [Conda]
        if: contains(matrix.os, 'macos')
        shell: bash -l {0}
        run: |
          conda info
          mamba list
          env

      - name: Build wheel
        shell: bash -l {0}
        run: |
          python${{ matrix.python-version }} -m pip install -U pip
          pip install auditwheel auditwheel-symbols
          python${{ matrix.python-version }} -m pip wheel -w dist .

      - name: Inspect wheel with auditwheel
        if: contains(matrix.os, 'ubuntu')
        shell: bash -l {0}
        run: |
          auditwheel show dist/proxsuite*.whl

      # - name: Repair wheel with auditwheel
      #   if: contains(matrix.os, 'ubuntu')
      #   shell: bash -l {0}
      #   run: |
      #     auditwheel repair dist/proxsuite*.whl

      - name: Start SSH session
        uses: luchihoratiu/debug-via-ssh@main
        with:
          NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
          SSH_PASS: ${{ secrets.SSH_PASS }}

      - name: Archive artifacts
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: dist

  release:
    needs: "build-wheel"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - uses: actions/download-artifact@v3

      - name: Publish package to TestPyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          verbose: true
          password: ${{ secrets.TEST_PYPI_API_TOKEN }}
          repository_url: https://test.pypi.org/legacy/

      - name: Publish package to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        if: |
          github.repository == 'simple-robotics/proxqp' &&
          (github.event_name == 'release' && github.event.action == 'published')
        with:
          user: __token__
          password: ${{ secrets.PYPI_TOKEN }}
